[package]
name = "Project_tables"
version = "0.1.0"
edition = "2024"
default-run = "Project_tables"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
mime_guess = "2.0.5"
rusqlite = { version = "0.40.1", features = ["bundled"] }
rust-embed = "8.12.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes-gcm = "0.10"
dotenvy = "0.15"
hex = "0.4"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
